spring:
  main.allow-bean-definition-overriding: true
  profiles:
    active: spring.profiles.active
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_db_task1
    username: postgres
    password: password
  jpa:
    show sql: true
    properties:
      hibernate:
      format_sql: true
---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prod_db_task1
    username: postgres
    password: password

